from enum import IntEnum


class GameErrorCode(IntEnum):
    OK = 200
    REGENERATION = 201
    CONNECTED = 202

    INTERNAL_CLASS_MATCHING_ERROR = -1
    INTERNAL_SERVER_LOGIC_ERROR = -2
    PAYMENT_ERROR = -3

    SOCKET_UNKNOWN = -101
    SOCKET_WRONG_FORMAT = -201

    NOT_ENOUGH_MONEY = -1001
    GAME_EVENT_OUT_OF_BOUNDARIES = -1102
    NOT_ABLE_TO_PLACE = -1003
    PLANT_NOT_GROWN = -1004
    PLANT_NOT_PLANTED = -1105
    CANNOT_USE_BUILDING = -1006
    NOT_ENOUGH_BUILDING_CONDITIONS = -1007
    GARDEN_NOT_PLACED = -1008
    BUILDING_NOT_PLACED = -1009
    INVALID_AMOUNT = -1010
    WORK_NOT_READY = -1011
    WORK_NOT_STARTED = -1012
    SPIN_NOT_GENERATED = -1013
    SPIN_NOT_ENOUGH_ITEMS = -1014
    ORDERS_NOT_ENOUGH_ITEMS = -1015
    ORDERS_NOT_READY = -1016
    ORDER_ALREADY_COMPLETED = -1017
    ORDER_NOT_ENOUGH_ITEMS_TO_COMPLETE = -1018
    ORDERS_NOT_ENOUGH_REROLLS = -1019
    CORRAL_ALREADY_MAX_ANIMALS = -1020
    BUSH_EXPIRED = -1021
    BUSH_NOT_EXPIRED = -1022
    BUILDING_ALREADY_MAXXED_UP = -1023
    DEPOSIT_ALREADY_ACTIVATED = -1024
    DEAL_HAS_BEEN_ALREADY_BOUGHT = -1025
    NO_SPACE_IN_INVENTORY = -1026
    BUILDING_LIMIT_EXCEEDED = -1027
    CANT_MOVE_OBSTACLE = -1030

    SPIN_NOT_READY = -10001


class GameError(Exception):
    def __init__(self, code: GameErrorCode) -> None:
        self.code = code
        super().__init__(code.name)
